### ISSUE TITLE
Autofocus Edit Existing Action Item

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#10]
## Feature Request
When editing an existing Action Item, the current text should be highlighted by default with the cursor active so a user can just start typing the changes as desired.

#### Story
**As a** member of a retrospective
**I want** the current text to be highlighted by default when I click the pencil on an existing Action Item
**So that** I can easily edit the existing Action Item without getting frustrated

#### Acceptance Criteria
**Given** the member is attending a retro
**When** they click the pencil on an existing Action Item
**Then** the text should be focused and highlighted by default

**Comment by Druage** [comment]
With the new UI controls I made, we can easily do this by using 'document.execCommand('selectAll', false, null);'

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
