### ISSUE TITLE
Internet Explorer Action Item Display

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#105]
## Bug report
The text of Action Items does not fit properly.

#### What is the actual(incorrect) behavior?
The text does not inside the box causing it difficult to view or edit Action Items.  Refer to image.

#### What is the expected(correct) behavior?
The text should be inside the Action Item Box.

#### Include any logs/screenshots below:
![image](https://user-images.githubusercontent.com/8965915/44239486-91963f80-a187-11e8-9346-7858e629fc91.png)

**Comment by Druage** [comment]
hahahahaha, that looks so horrible

**Comment by abarna10** [comment]
Base issue is resolved. A new issue will be opened to investigate what it will take to bring IE up to parity.
