### ISSUE TITLE
Thought Item Focus Timer Countdown

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#12]
# Feature Request
Requests have been provided asking for a timer that is visible when discussing retro items to ensure no single item takes too much time.

# Story  
**As** facilitator of a retrospective
**I want**  a timer to be visible when I focus in on a Thought
**Then** a timer is displayed to the left of the "mark discussed" checkbox and starts counting down from 3 minutes

# Acceptance Criteria
**Given** a individual is facilitating a retrospective through RetroQuest
**When** they focus on a Thought
**And When** the timer reaches 0:00
**Then** text appears to the left of the timer that says "Time's up!"

**Given** Gene decides the team is done discussing a thought
**When** he marks the thought as discussed OR closes the modal
**Then** the timer is reset

**Comment by mikesmithson** [comment]
@abarna10  - is there still interest in this?

**Comment by RandomAshes** [comment]
We've added a timer to the main retro page, maybe that will suffice for this situation.
