### ISSUE TITLE
Send open Action Items to a Team Communication Channel

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#130]
## Feature Request
Feedback has been provided requesting the ability to integrate the open Action Items to a teams communication channel (e.g. Spark / Slack) for a reminder to take action on.

#### Story
**As a** member of a team using RetroQuest
**I want** to be able to send the open action items (e.g. file/text) to my teams communication channel (e.g. Slack, Spark, Backlog, email)
**So that** the team can be reminded of the open Action Items that need to be completed are made apparent to the team members after the retrospective has concluded

#### Acceptance Criteria
**Given** a member of a Team Board logs into RetroQuest
**When** invoke some action that prompts them to where they want the open Action Items to be delivered
**Then** open Action Items are delivered to the desired location

#### Notes
- Where will the user prompt the invocation to send the open Action Items?
- What will the communication channels be that we integrate with?
- What will be the format of the open Action Items when delivered to the communication channel?

**Comment by dpainte7** [comment]
I implemented this externally to RetroQuest with an integration that links the RQ api to Slack.  I'm wondering if that's a better way forward than building it in directly?  Happy to show some examples of what I did if anyone's interested.

**Comment by LowBudgetMan** [comment]
RetroQuest does have an API that could be used for this and we're planning to keep our API organized and stable to enable third party integrations. With that in mind at this point in time we're taking the direction of leaving those integrations outside of RetroQuest and up to other services.
