### ISSUE TITLE
Space in thought is rendered incorrectly during edit (and subsequent save)

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#139]
## Bug report
Spaces is rendered incorrectly during edit.

#### What is the actual(incorrect) behavior?
When you enter an Space into a thought (at the beginning OR more than one while typing), and then edit it, it renders the XML entity, which then saves as an XML entity.

#### What is the expected(correct) behavior?
Spaces should be saved as " ".

#### Steps to Reproduce
**Scenario 1**
1. Enter thought with an space at the first position (and save).  The space is rendered incorrectly.

**Scenario 2**
1. Edit the thought.  Place two spaces in the text (not the first character) one after the other.
2. Save the edited thought.  The space is rendered incorrectly.

**Comment by abarna10** [comment]
Tested and launched.
