### ISSUE TITLE
auto trigger and fill of action item card

### ISSUE THREAD

**Issue by dnykiel1** [FordLabs/retroquest#158]
## Feature Request
to provide option to trigger an action item during review of a retro card and to maintain the association; and to reflect the "like" count from the retro card in the action item

#### Context
An automatic link from an action item to the source retro card maintains context of action without having to copy/paste or summarize the source retro card -- plus it saves time.  Reflecting the "like" count from the retro card in the action item provides an option for prioritizing actions.

#### Story
**As a** retro lead/facilitator
**I need** a button on the source card active during review that when clicked creates an action item card either linked to the source card/or pre-populated with the source card text to retain context AND that reflects the "like" count of the source card on the action card
**So that** context of the action is not lost and the retro process is not slowed by having to copy/paste or summarize (due to space limitations) the source card to ensure source integrity AND there is an option to sort the action items by the "like" counts for prioritizing.

#### Acceptance Criteria
**Given** (some context)
**When** (some action is carried out)
**Then** (some consequences)

**Comment by RandomAshes** [comment]
Action items might be associated to a thought, but not necessarily every action item. We don't know what that would look like. We're going to close this until someone has a more fleshed out idea of what that would look like.
