### ISSUE TITLE
Team names are pre-populated with dashes instead of spaces when using a bookmark

### ISSUE THREAD

**Issue by thedavidharris** [FordLabs/retroquest#175]
## Bug report

When going to a team's board that requires login, and the board name contains spaces, Retroquest is inserting dashes into the spaces instead.

This arises because the actual /team URLs use dashes instead of spaces, so when it redirects to /login it uses those dashes as well. Replacing the dashes with `%20` does induce the correct behavior.

#### What is the actual(incorrect) behavior?

Team name is pre-populated with dashes (`-`) instead of spaces

#### What is the expected(correct) behavior?

Team name should be correctly populated with spaces.

Team name should be using spaces

#### Please provide your browser and OS versions:

MacOS, Chrome

**Comment by MarkJRust** [comment]
Another team has reached out and described this issue

**Comment by thedavidharris** [comment]
I put a draft PR up here: https://github.com/FordLabs/retroquest/pull/198. That fixes the root of it, but have to verify to make sure nothing else is broken by it that requires updating.
