### ISSUE TITLE
Remove overlay from thoughts on archived boards

### ISSUE THREAD

**Issue by adandach** [FordLabs/retroquest#177]
## Feature Request
Remove overlay on thoughts in archived boards.

#### Context
It is difficult to read thoughts on archived boards due to the opacity. Given the board is archived, all thoughts are "complete" therefore an indicator that they have been discussed is not needed.

#### Story
**As a** team member
**I want** the ability to see archived thoughts
**So that** I can reference them later

#### Current Design
<img width="1512" alt="screen shot 2019-01-25 at 4 44 57 pm" src="https://user-images.githubusercontent.com/5607510/51775105-94944500-20c2-11e9-9cc1-f0f6af7be647.png">

**Comment by abarna10** [comment]
This issue was closed by the above pr.
