### ISSUE TITLE
Alert Internet Explorer Users of limited functionality

### ISSUE THREAD

**Issue by MarkJRust** [FordLabs/retroquest#182]
**Feature Request**

As a user of Internet Explorer
I want to be alerted that IE has limited support from RetroQuest
So that I do not assume that RetroQuest is broken

**Acceptance Criteria**

Given I open RetroQuest in IE
When the page loads
Then I'm alerted that my browser has limited support from RetroQuest

**Comment by LowBudgetMan** [comment]
Since IE support has been discontinued, people should not be using the browser. Rather than adding in functionality with no clear removal date, we're instead going to opt for the site just not working on IE.
