### ISSUE TITLE
Ability to unstar/unlike a thought

### ISSUE THREAD

**Issue by MarkJRust** [FordLabs/retroquest#183]
**Feature Request**

As a user of RetroQuest
I need the ability to unstar/unlike a thought
So that when I make a mistake I can undo it

**Acceptance Criteria**

Given I have starred/liked a thought
When I click to remove it 
Then the star/like is removed

**Comment by Druage** [comment]
But I like it that it doesn't do this! :(

**Comment by mikesmithson** [comment]
@MarkJRust - is there still interest in this?

**Comment by MarkJRust** [comment]
@mikesmithson its been a very long time since I've read the feedback coming through to retroquest

**Comment by justinwhite** [comment]
Just noticed this today - it seems like a single person can indefinitely upvote a card as opposed to the star count toggling for that individual.

**Comment by RandomAshes** [comment]
The ability to have single starts and like and unlike a thought is something that we've been having discussions about for awhile. This should be moved to a discussion not an issue.
