### ISSUE TITLE
Ability to limit stars/likes to 1

### ISSUE THREAD

**Issue by MarkJRust** [FordLabs/retroquest#186]
**Feature Request**

As a user of RetroQuest
I need the ability to limit the number of stars/likes to 1
So that I can limit abuse of the functionality

**Acceptance Criteria**

Given I have limited the number of stars/likes
When I select a thought to star/like
Then then I cannot increment the star/like count beyond 1

**Comment by Druage** [comment]
Maybe with user accounts and some kind of permission system...

**Comment by Druage** [comment]
g

**Comment by awtrimpe** [comment]
Limiting by MAC address might be better to slightly obscure votes and not have to handle account permissions, password resets, etc.

**Comment by mikesmithson** [comment]
@MarkJRust - is there still interest in this?

**Comment by MarkJRust** [comment]
This could be an interesting experiment to run 🤔

**Comment by rkennel** [comment]
Duplicate issue.  I am closing this one
