### ISSUE TITLE
Enable resetting of password

### ISSUE THREAD

**Issue by sgraha75** [FordLabs/retroquest#19]
## Feature Request
As RetroQuest is growing in size and usage, requests have been made that will create and assign a new "Admin" role to a Team Board.  Initially, the request is to enable a password reset functionality to this "Admin" role.

This **story writing is in progress** and needs more thought as we attempt to integrate a new "Admin" role into this request, based on recent feedback requests.  This story will likely be split into multiple stories.

#### Story
**As a** Team Board Admin
**I want** to be able to reset the password of my board
**So that** as members join or leave I can keep the retro confidential to the team 

#### Acceptance Criteria
**Given** a member has left the team 
**When** a retro facilitator changes the password (needs to input their team board name, current password, new password, and confirmation of the new password)
**Then** all users of the board must log in using the new password

**Given** a retro facilitator is attempting to change the password
**When** they input the wrong current password for the team board name
**Then** they are provided a message indicating that the Incorrect board or password was provided

**Given** a retro facilitator is attempting to change the password
**When** they provide the new password and confirm of the new password that do not match
**Then** they are provided a message indicating new password and confirmation of the new password must match 

#### Note
Verification of the password policy must occur.

**Comment by rkennel** [comment]
Do we allow only the facilitator to change the password or anyone on the team?  Currently there is no concept of user, just team.

**Comment by sgraha75** [comment]
No, anyone who has access to the board could change it. The use of "facilitator" is the most likely person to change it, but it should not be locked down, for now. There may be a future case to create user types, but that is outside the scope of this story.

**Comment by RandomAshes** [comment]
We may implement a version of this if we ever swap to user accounts, but until then, access controls would be contrary to the anonymity that team accounts provide.
