### ISSUE TITLE
Download CSV Functionality is Broken

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#191]
## Bug report
Download CSV Functionality is no longer working correctly

#### What is the actual(incorrect) behavior?
Clicking on Download CSV takes the user to a blank screen with no file being downloaded.

#### What is the expected(correct) behavior?
The screen should not change and a CSV file should start to download.

**Comment by Druage** [comment]
Its not broken anymore I fixed it.

**Comment by Druage** [comment]
This is already prod so I am going to close it.
