### ISSUE TITLE
Sell this puppy on the market!

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#205]
## Request

Start charging money for this so we can host this for external companies. There are several competing retro web apps that charge money and have less features or about the same as us, yet we dont have an external offering!

![Crying Pikachu](https://media.giphy.com/media/12Bpme5pTzGmg8/giphy.gif)

**Comment by coachnate** [comment]
This certainly raises the question to "Ford being a software company"  - why can't this be marketed and sold? Do you need help finding the people in legal to start this conversation? I'm happy to help introduce/help find them.

**Comment by lndobryden** [comment]
At this time we don't have any plans to sell this as a SAAS offering. I'd like to see efforts in the meantime focused on making it easier to self-host and get more community contributions for a more compelling product. Open to revisiting this idea at a later date.
