### ISSUE TITLE
What to do about huge action item list on retro page.

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#217]
On the main retro page a common tactic is the use the action items list as some sort of archived history by never deleting any of them. This practice feels really wrong, especially because over time it will make the page load time unacceptable. Any ideas on what do do?

My thoughts on how to solve this are:

1. When action items are closed they get moved to the archive in which their date range lines up in.

2. There in a new archive list can gets generated only for action items. We can still display these in the archive route.

**Comment by RandomAshes** [comment]
Completed action items go to the archives page right now when someone ends a retro. If there's too many action items on a retro page that just means the team needs to take action on their action items. This might not be a code problem, it seems more like a lack of understanding how to utilize action items while conducting a retro.
