### ISSUE TITLE
Header Redesign

### ISSUE THREAD

**Issue by chiptopher** [FordLabs/retroquest#22]
## Feature Request
Redesign the header of the page to be separated from the "Action Bar", the section of the header that contains the three buttons.

The reason for this redesign is to make the page not only look better but to provide a distinct section for actions such as "Download CSV" and "End Retro" so that it is visually uncluttered and leaving more space for future additions.

#### Design
<img width="1130" alt="screen shot 2018-07-05 at 2 30 28 pm" src="https://user-images.githubusercontent.com/18236455/42341131-067399a4-8060-11e8-8127-395e797c00da.png">

More design specifications can be found at this [Zeplin link](https://zpl.io/aRYdZjz), and questions can be directed to @Druage .

**Comment by abarna10** [comment]
@Druage Header redesign looks good in DEV RetroQuest.
