### ISSUE TITLE
Cannot create a new board

### ISSUE THREAD

**Issue by MarkJRust** [FordLabs/retroquest#225]
## Bug report
When attempting to create a new board, the following error is received: "HV000028: Unexpected exception during isValid call."

#### Include any logs/screenshots below:
![image](https://user-images.githubusercontent.com/7401983/57373540-9dd38a00-7166-11e9-809c-68d9186f9677.png)

**Comment by Druage** [comment]
Nick fixed this today! Issue was were didn't set the HTTP_PROXY values in PCF, they were needed for the recaptcha to talk to Google.
