### ISSUE TITLE
Upgrade to current release of Gradle

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#226]
## Feature Request
Upgrade to a newer version of gradle

#### Context
Current version of retroquest uses gradle 4.6.  Newest stable version of gradle is 5.4.  Upgrading will take advantage of the newest benefits of gradle.

#### Acceptance Criteria
**Given** a synchronized buildable workspace
**When** I perform a gradle build
**Then** the build completes successfully

#### Notes
- All variants of gradle build must pass
- Gradle versions are different in each project root (4.6), api (3.5).  Is it necessary to have both wrappers?

**Comment by Druage** [comment]
Very true we have been lacking by using a really old version of Gradle. I see the potential of general updates by themselves as being a big win.

**Comment by mikesmithson** [comment]
Currently updated to 6.5.1. On develop, deploying on next prod build.
