### ISSUE TITLE
Implement open graph protocol to make summary snapshots available in social media.

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#227]
## Feature Request
Implement open graph protocol and corresponding twitter metadata so that when I share links in social media platforms a summary snapshot of the web page is shared.

#### Acceptance Criteria
**Given** Slack, Webex Teams, Twitter, Facebook, LinkedIn
**When** I share a link to retroquest on the social media platform
**Then** The following is displayed:
- RetroQuest Title: RetroQuest - {Some Snappy Catchphrase used to brand retroquest}
- RetroQuest logo
- URL link to Retroquest

#### Notes
- [Open Graph Protocol](http://ogp.me/)
- [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html)

**Comment by mikesmithson** [comment]
@rkennel - is there still interest in this?

**Comment by rkennel** [comment]
This was implemented a long time ago by me.  I forgot to close the issue.
