### ISSUE TITLE
Ability to rename board name

### ISSUE THREAD

**Issue by MarkJRust** [FordLabs/retroquest#242]
#### Context
"This is great tool for our retros, however we are in constant change and I cannot find a way to change the name of the Retro Board... we want to keep the action items but we changed the name of our team. Can someone please help me changing it?"

#### Story
**As a** team who has recently changed their team name
**I need** a way to change our board name
**So that** our team stays current

#### Acceptance Criteria
**Given** I need to change my board name in RetroQuest
**When** I select to rename it to something new
**Then** the login name will change as well as the URL to access the board

**Comment by mikesmithson** [comment]
@MarkJRust - is there still interest in this?

**Comment by MarkJRust** [comment]
@mikesmithson this was an old piece of feedback, not sure how often people desire this or run into this issue now.

**Comment by coachnate** [comment]
I find this helpful - I end up creating new boards more often than I think I should be.

**Comment by RandomAshes** [comment]
Until we have user accounts and permissions setup, we can't do this. See comments on issue #19.
