### ISSUE TITLE
Column Title Changes Do Not Persist when using Emojis in Title

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#251]
#### What is the actual(incorrect) behavior?
When I change the title of the columns, other users do not see it.  If I close the browser and come back, the titles revert to the default titles. 

#### What is the expected(correct) behavior?
Column title changes should be cascaded to other users and should persist to new sessions

#### Please provide your browser and OS versions:
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by rkennel** [comment]
@Druage - let me know your thoughts on this one.  If you think its worth implementing I can make the necessary code changes.

**Comment by mikesmithson** [comment]
it looks like you can type the characters like :-) and those persist but if you enter the unicode characters for the same emoji, it won't persist since the backend data type doesn't currently support unicode characters. Is this something you are still interested in pursuing?

**Comment by rkennel** [comment]
Yes, most websites today support emojis.  Is it high priority...?  Probably not

**Comment by msuzio** [comment]
Seems possible... https://dev.mysql.com/doc/refman/8.0/en/charset-unicode.html

**Comment by lndobryden** [comment]
Since we moved to recommending postgres as the preferred database this appears to have been resolved.
