### ISSUE TITLE
The Retroquest admin credentials are not being decoded properly

### ISSUE THREAD

**Issue by mikesmithson** [FordLabs/retroquest#252]
## Bug report
when hitting the api/admin/metrics/team endpoint, an unauthorized response is generated when passing the correct admin credentials.

PCF Logs:
[io-8080-exec-10] o.s.s.c.bcrypt.BCryptPasswordEncoder : Encoded password does not look like BCrypt

#### What is the expected(correct) behavior?
should be authorized to hit the api/admin endpoints

**Comment by LowBudgetMan** [comment]
Going to take a look at fixing this, or potentially removing the admin endpoints.
