### ISSUE TITLE
Allow direct edit of retrospective items

### ISSUE THREAD

**Issue by mchatterley** [FordLabs/retroquest#256]
## Feature Request
Currently if want to edit an item on the board I have press the edit button.  I would prefer to be able to start editing directly after clicking on item.

#### Story
**As a retrospective participant user** 
**I need to edit the items I create directly** 
**So that I can complete my retrospective more quickly.**

**Comment by RandomAshes** [comment]
With the current design, this is not possible because clicking on the text, that is used to open up the retro item in a modal.
