### ISSUE TITLE
JIRA Integration for Action Items

### ISSUE THREAD

**Issue by mchatterley** [FordLabs/retroquest#257]
#### Story
**As a retrospective admin** (type of user)
**I need a jira integration** (some goal)
**So that I can easily turn my action items into stories so that I can ensure they'll be completed.** (some benefit)

**Comment by rkennel** [comment]
Excellent idea.  Can you expand upon how you see that integrating into Jira?  Is that a user story?  Is it a ticket.  It'd be helpful if you described what would work best in your opinion.

**Comment by mchatterley** [comment]
@rkennel ideally I would like the option of what jira type they would translate into.  I would probably use stories but I could see others using tasks or defects too.

**Comment by lndobryden** [comment]
Hi @mchatterley,
RetroQuest does have an API that could be used for this and we're planning to work on our documentation (see #303 as a start) as well as keep our API organized stable to enable third party integrations. With that in mind at this point in time we're taking the direction of leaving those integrations outside of RetroQuest and up to other services.
