### ISSUE TITLE
Prevent multiple votes

### ISSUE THREAD

**Issue by mchatterley** [FordLabs/retroquest#258]
## Bug report
Users seem to be able to vote for their own items and vote for the same item multiple times.   This reduces the value of the voting feature as one user can easily distort the results.

#### What is the actual(incorrect) behavior?
I can create an item, vote for my own item and vote for it multiple times.

#### What is the expected(correct) behavior?
Users can't vote for their own issues or vote multiple times.

#### Please provide your browser and OS versions:
Windows chrome

**Comment by lndobryden** [comment]
Hi @mchatterley,

We've discussed adding this as a configuration per board, but given we don't have individual login and don't track users in any way that makes this very difficult to implement reliably.

In many cases being able to upvote your own items multiple times is a feature. On my teams we'll usually tell people they have a fixed number of votes and use the honor system. If I want to put my three votes on an item I entered on something I think is really important, RetroQuest and my team norms allow me to do that.

Can you speak more to the situation you're encountering where you think limiting votes would be necessary?

**Comment by meganmajewski** [comment]
I agree @lndobryden - I think the ability to vote for your own item is a feature we should keep.

But I am wondering if there is some way we could achieve the feature request to prevent people from voting multiple times for an item.
Maybe some configuration options could be provided per board that lets users assign X number of votes per person, and the option to enable/disable ability to vote on a card multiple times. @mchatterley does this help your use case?

**Comment by RandomAshes** [comment]
Closing as this should be a discussion and not an issue until a consensus has been made.
