### ISSUE TITLE
RetroQuest Query - input not being recorded, time-out issue?

### ISSUE THREAD

**Issue by mdavenp2** [FordLabs/retroquest#273]
## Bug report
(delete this section if not applicable)

## Feature Request
(delete this section if not applicable)

#### Context
(provide any rationale or context for this feature)

#### Story
**As a** retroquest user
**I need** clarity on whether there is a 'time-out' after inactivity in the tool 
**So that** to avoid losing input ie new 'thoughts' or editing existing thoughts

#### Acceptance Criteria
**Given** (some context)
**When** (some action is carried out)
**Then** (some consequences)

**Comment by lndobryden** [comment]
Hi @mdavenp2,

I don't believe there's a specific timeout for inactivity. It's possible that the websocket connection to the backend was lost due to internet instability or some other cause. If that's the case that behavior might get better once #281 is merged.

**Comment by mdavenp2** [comment]
Hi Lee – many thanks for the update.

Many of our team have experienced this now so hopefully when the next action takes place it will resolve the issue.  In the meantime we refresh before adding comments, just in case 😊

**Comment by LowBudgetMan** [comment]
Stomp got merged in with Pull Request #281. @mdavenp2 are you guys still seeing the issue?

**Comment by mdavenp2** [comment]
Hi, yes still seeing the issue sometimes.  I was watching a demo today & action did not appear after entering.
Could the issue be linked to having more than 1 retro board open at a time? Also, I notice someone else has opened a similar 'bug' in the last week.
Many thanks.

**Comment by LowBudgetMan** [comment]
Alright, thanks @mdavenp2 for letting us know! We merged in #324 which seems to be the same issue you were having. Any chance it's resolved now?

**Comment by mdavenp2** [comment]
Hi Nick,
The issue of not recording comments / actions comes & goes.

My colleague, Axel, recently had this issue in recording an action plan.  He also refreshed & entered it again but it still didn’t record.

Any insight into why this happens would be great as the retroquest tool is something that we use regularly.
Many thanks for your help,
Melanie.
