### ISSUE TITLE
Replace ts-stomp as a ui dependency

### ISSUE THREAD

**Issue by adandach** [FordLabs/retroquest#276]
Migrate away from [@elderbyte/ts-stomp](https://www.npmjs.com/package/@elderbyte/ts-stomp). The Github repo is no longer public and the package was last deployed more than 2 years ago.

Potential replacement: https://github.com/stomp-js/stompjs

**Comment by rkennel** [comment]
Work in progress

**Comment by LowBudgetMan** [comment]
@rkennel since the PR has been merged in, can we close this issue?
