### ISSUE TITLE
Excessive // @ts-ignore comments in jest tests

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#278]
## "Bug" report
There are 20+ occurrences of @ts-ignore in the codebase.  Putting this type of comment in the codebase creates noise and shortcircuits the strong typing provided by TypeScript.

#### Notes
This mostly occurs in the tests when we are creating Mock objects and casting them to a type without creating a full implementation of that type

```
    // @ts-ignore
    mockActionItemService = {
      fetchActionItems: jest.fn().mockReturnValue(of([]))
    } as ActionItemService;
```

**Comment by RandomAshes** [comment]
This is no longer an issue after refactoring the front end to React.
