### ISSUE TITLE
Separate UI Tests from E2E tests

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#282]
## Feature Request
RetroQuest makes use of unit tests (Jest) and end to end tests (protractor) to make up its automated testing strategy.  Currently, the end to end tests are trying to accomplish multiple tasks:
- UI Tests 
- Integration Tests
- End to End Tests

The other challenge with these tests is that they take a long-time to execute.  Almost 53 seconds on a computer with a 12 core process for just 21 tests compared to 4.4 seconds to run 326 unit tests.  This makes it more hassle for engineers to consistently run the tests

**E2E Test Execution**
```
Executed 21 of 23 specs INCOMPLETE (2 PENDING) in 38 secs.
[HPM] Client disconnected
[10:49:40] I/launcher - 0 instance(s) of WebDriver still running
[10:49:40] I/launcher - chrome #01 passed
Done in 52.72s.
```
**Unit Test Execution**
```
Test Suites: 51 passed, 51 total
Tests:       326 passed, 326 total
Snapshots:   0 total
Time:        3.836 s, estimated 7 s
Ran all test suites.
Done in 4.42s.
```

## What are We Doing?
Separate UI tests from protractor to run quickly and give confidence in the behavior of the UI.

## What are We not Doing?
- Adding additional UI tests coverage
- Testing UI functionality that cannot be easily imitated by JSDOM and thus won't give us confidence of stable software
- Replacing protractor for true end to end tests

## What does it look like to be Done?
- UI Tests extracted from protractor likely into Jest Test Runner
- Tests run quickly and accurately

## Design
- This will likely make use of [Angular Testing Library ](https://testing-library.com/docs/angular-testing-library/intro/)

**Comment by lndobryden** [comment]
@rkennel Is this complete? From what I can tell it looks like #284 closes this issue
