### ISSUE TITLE
As a release manager I need a way to be able to easily find all the retrospectives that relate to my project

### ISSUE THREAD

**Issue by mchatterley** [FordLabs/retroquest#283]
#### Story
**As a release manager** 
**I need a way to be able to easily find all the retrospectives that relate to my project**
**So that I can prioritize the issues that multiple teams are facing and so that I can find relevant boards more easily**

The tool works really nicely for individual boards but how does a release or tools manager see all the boards that relate to them?  I think this concept needs to be added to the tool.  Otherwise the retrospectives become hard to find if the users no longer have each board id and password handy that they care about.

For an enterprise tool, on entry into the tool I would like to have way to search for boards that I care about as well as a view to let me quickly navigate to all the retrospectives I have participated in.

**Comment by rkennel** [comment]
@mchatterley thank you for the suggestion.  One of the main principles of RetroQuest is providing a safe space for teams to provide feedback for improvement.  A key to providing that safe space is anonymity.  How would you propose we protect anonymity while providing this functionality?

Would you see this as an optional "Login with <Favorite SSO Provider>" feature that allowed user management?

**Comment by RandomAshes** [comment]
This feature isn't possible without user management, which, like rkennel said, conflicts with the interest of providing a safe space through anonymity. Maybe if we figure out how to get user accounts in a safe way, we can have a view where you can see all the teams you are a part of.
