### ISSUE TITLE
Items in the third column, once created, seem to have the wrong remaining character count

### ISSUE THREAD

**Issue by wjruffing** [FordLabs/retroquest#287]
## Bug report
(delete this section if not applicable)

#### What is the actual(incorrect) behavior?
Create an item and save it.
EDIT that item (card)
As you add additional characters to the item, the character count turns RED *BEFORE* you get to zero (indicating no more characters are available and the user is over).
It almost appears that the remaining character count is being calculated based on the number of characters that were already in the item BEFORE you began editing it (instead of the MAX number of characters allowed in ANY item).
In my case, I was changing something in the third column, but not sure if it exists in other columns or not).

#### What is the expected(correct) behavior?
Characters should be able to be typed (and saved) as long as the number of characters left is above or equal to zero.

#### Please provide your browser and OS versions:
Version 90.0.4430.93 (Official Build) (32-bit) - on Ford IT managed laptop

**Comment by adandach** [comment]
Thanks for opening the issue @wjruffing. The character count turns red when there are fewer than 50 characters remaining. I recognize that is not very intuitive. I am making a change where the character count is yellow between 50 characters and 1 character remaining. At 0 characters remaining it will turn red.
