### ISSUE TITLE
Remove Ford Specific CI/CD and Configuration from Repository

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#293]
## Feature Request
Remove Ford Specific CI/CD and Configuration from Repository

#### Context
Currently the repository has Jenkins scripts and Cloud Foundry configuration that is specific to the deployment of RetroQuest at Ford.  This should be removed as it is specific to a single deployment of Retroquest.

Note:
The newly added Git Actions script should remain as it is performing a useful continuous integration function to any person interested in contributing to Retroquest.

**Comment by lndobryden** [comment]
This was addressed by #302
