### ISSUE TITLE
Replace Default Spring Boot Logo during startup with the S.S. Market Speed

### ISSUE THREAD

**Issue by rkennel** [FordLabs/retroquest#294]
## Feature Request
Sadly when the ship scripts were deleted, we lost our beloved SS Market Speed.
```
              |    |    |
             )_)  )_)  )_)
            )___))___))___)\\
           )____)____)_____)\\\\
         _____|____|____|____\\\\\\__
---------\ S.S. Market Speed /---------
  ^^^^^ ^^^^^^^^^^^^^^^^^^^^^
    ^^^^      ^^^^     ^^^    ^^
         ^^^^      ^^^"
```

#### Story
**As a** RetroQuest Developer
**I need** to see the SS Market Speed
**So that** I get motivated to ship some code

#### Acceptance Criteria
**Given** Backend Spring Boot Server
**When** Spring Boot performs startup
**Then** the SS Market Speed is displayed

#### Notes
[Customizing the Spring Banner](https://docs.spring.io/spring-boot/docs/2.4.5/reference/html/spring-boot-features.html#boot-features-banner)

**Comment by nhajratw** [comment]
IMO -- it's cute, but noisy and unnecessary :)

I like to see:
```
$ ./gradlew bootRun
2021-06-09 13:48:53.037  INFO 90914 --- [  restartedMain] c.ford.labs.retroquest.MainApplication   : Started MainApplication in 5.862 seconds (JVM running for 6.24)
```
