### ISSUE TITLE
RetroBoard Suddenly Unresponsive - Need to Refresh Page to Reactivate

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#30]
## Bug report
As we are facilitating a retrospective using RetroQuest, the team board become unresponsive.  No message was provided and the only way to make the page respond to my input was to refresh the browser.

#### What is the actual(incorrect) behavior?
The page become inactive in the middle of the team retrospective.  Their was no message of this to me as the user and the only way to make the board usable again was to refresh the board.

#### What is the expected(correct) behavior?
The page should not become unresponsive as I am facilitating my retrospective.

#### Please provide your browser and OS versions:
Chrome: Version 67.0.3396.99 (Official Build) (64-bit)
High Sierra 10.13.2

**Comment by Druage** [comment]
I have seen this happen before as well

**Comment by abarna10** [comment]
This has been migrated to PROD and appears to have resolved the issue.
