### ISSUE TITLE
RetroQuest Initial Set of Metrics Reporting

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#32]
## Feature Request
In order to better understanding the growth in user engagement of RetroQuest, we need to start building out metrics related to its usage.

#### Story
**As a** Trusted Committer of RetroQuest
**I Want** to be able to capture and display the following metrics on our radiator dashboard:
 - Total Number of Reviews
 - Total Avg Review Rating (Discard 0 star reviews at the moment.  There is no way for a user to input 0 stars as it is the default.)
 - Total Number of Team Boards 
**So That** we can understand how RetroQuest is being used by community

#### Note
This is an initial metrics story, we can build on additional metrics in the future.  Additional stories, will be to created to provide a date range to perform this data given the provided date range.

**Comment by chiptopher** [comment]
How do we want to authorize who is and who is not a trusted committer? Do we want to do it similar to the way the feedback endpoint is handled?
