### ISSUE TITLE
Add separator between column header and thoughts / action items

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#33]
## Feature Request
The current design for displaying the number of discussed thoughts is problematic, mainly being that the header has too much content inside of it. This redesign separates out this column count and puts in a seperator.

#### Design
![count seperator](https://user-images.githubusercontent.com/6293337/42396930-d1e15fb4-8131-11e8-890e-923b32c2dde1.png)

**Comment by abarna10** [comment]
@Druage I see a few new changes in the DEV version of RetroQuest.  I am listing the noted issues as a part of this story: 

1) When editing the column title, hitting enter does not save the changes to the column name.
2) When viewing RetroQuest on a Mobile Device, the background color does not stretch the entire page.

**Comment by Druage** [comment]
These have been both turned into issues and are fixed! They are actually waiting in PR merges

**Comment by sgraha75** [comment]
@Druage @abarna10 Verified that these are working as expected in DEV, as well as the original story.

**Comment by abarna10** [comment]
The changes related to this issue have been migrated to PROD.
