### ISSUE TITLE
Scroll doesn't work on Android Chrome

### ISSUE THREAD

**Issue by fornster** [FordLabs/retroquest#331]
## Bug report
Scrolling through items is impossible on mobile

#### What is the actual(incorrect) behavior?
Any press on a topic makes it larger and overrides the scroll 

#### What is the expected(correct) behavior?
Can scroll through a list of topics

#### Please provide your browser and OS versions:
Chrome 91.0.4472.120 and Android 11

**Comment by tsatam** [comment]
We have disabled the ability to drag cards on mobile for now. We welcome any suggestions on how to allow for this functionality on mobile devices.
