### ISSUE TITLE
End Retro Button Doesnt Clear Cards

### ISSUE THREAD

**Issue by DSmedley** [FordLabs/retroquest#332]
#### What is the actual(incorrect) behavior?
When clicking the End Retro button, the cards disappear but upon refreshing the page all the cards come back. The archives are still created but the cards also still exist in the current retro.

#### What is the expected(correct) behavior?
Hitting the End Retro button should clear all cards from the current retro and create an archive. 

#### Please provide your browser and OS versions:
MacOS Big Sur in FireFox

**Comment by Druage** [comment]
I can duplicate this, fixing soon

**Comment by tsatam** [comment]
We have now fixed this issue. Thank you for your submission!
