### ISSUE TITLE
Default Dark/Light mode to OS settings

### ISSUE THREAD

**Issue by dctid** [FordLabs/retroquest#370]
## Feature Request
Default Dark/Light mode to OS settings

#### Context
Most sites now default to the OS dark/light mode settings, even if you don't login and choose in preferences or settings.

#### Story
**As a** Ford User who has to delete *.ford.com cookies all the time to make stuff work 
**I need** RetroQuest to default to my system Dark/Light mode 
**So that** I don't have to go in and select dark mode every time I delete my cookies

#### Acceptance Criteria
**Given** I just cleared *.ford.com cookies
**When** login to my board 
**Then** The dark/light mode is the same as my OS setting

**Comment by tsatam** [comment]
This seems pretty achievable using the `prefers-color-scheme` media query.

**Comment by dctid** [comment]
Because theme can be changed in the settings and seems to be stored in local storage (returning users get what they selected if they don't clear storage), this probably needs to combine preferred OS theme and the settings selected one if it's in local storage.

One way to query theme in js is: `let dark = window && window.matchMedia && window.matchMedia("(prefers-color-scheme:dark)").matches`

**Comment by RandomAshes** [comment]
Closing this as its been completed
