### ISSUE TITLE
Move Retro Page to React

### ISSUE THREAD

**Issue by LowBudgetMan** [FordLabs/retroquest#374]
Continuing the React Rewrite, we need to move the main Retro page to the new framework.

Misc:
- [x] Update column header titles
- [x] Write cypress tests 
- [x] Sorting columns
- [x] Write cypress tests
- [x] "Give Feedback" button
- [x] "Download CSV" button
- [x] "Archive Retro" button
- [x] Make clicking on thoughts open thought modal
- [x] Make it so you can add an action item from thought modal
- [x] Ensure thought gets marked as done once action item is made 
- [x] Disable animations in thought modal
- [x] Make clicking on action items expand
- [x] Added mobile column navigation and swipe events

Styling:
- [x] CSS column Transitions
- [x] Style completed items better
- [x] Overall style pass
- [x] Style archive retro modal
- [x] Mobile Styles
- [x] Ensure everything works in dark mode

Bugs:
- [x] Edit action item assignee makes call twice when user clicks enter (should only call once)

Action Items:
- [x] Create new
- [x] Delete
- [x] Edit task
- [x] Edit Assignee
- [x] Mark and unmark as complete

Thoughts:
- [x] Create new
- [x] Delete
- [x] Edit task
- [x] Edit Assignee
- [x] Mark and unmark as discussed

**Comment by aclift19** [comment]
Branch: https://github.com/FordLabs/retroquest/tree/react-retro-page
