### ISSUE TITLE
Ampersand in thought is rendered incorrectly during edit (and subsequent save).

### ISSUE THREAD

**Issue by bhoogter** [FordLabs/retroquest#38]
## Bug report
Ampersand is rendered incorrectly during edit.

#### What is the actual(incorrect) behavior?
When you enter an Ampersand into a thought, and then edit it, it renders the XML entity, which then saves as an XML entity.

#### What is the expected(correct) behavior?
When editing the thought, the Ampersand-amp-semicolon combination should be rendered back to a simple ampersand.

#### Steps to Reproduce
1. Enter thought with an ampersand (and save).  The ampersand is rendered naturally.
1. Edit the thought.  The ampersand is rendered as an entity  `&amp;` for editing.
1. Saving the thought displays the literal `&amp;` inside the thought now.
1. It is assumed repeated editing-saving would increase the number of `amp;` trailing.

**Comment by abarna10** [comment]
This has been fixed, tested, and shipped to PROD.
