### ISSUE TITLE
Radiator view of the team's action items

### ISSUE THREAD

**Issue by saur24** [FordLabs/retroquest#40]
#### Context
I have heard from user interviews and general feedback that teams need to be reminded more of their action items so they stick to them. I found that teams do not review them actively unless they are front and center in their workspace. One person said they add action items to their team board and review them every day in daily standup.

What if we provided a "view" of a team's board focused on the action items that they could throw on a team radiator? If you are not familiar with radiators, read this article: https://www.agilealliance.org/glossary/information-radiators/.

**Comment by abarna10** [comment]
Testing revealed a bug with this functionality. When switching to the radiator view and turning on auto-scroll. If you switch back to the retro view, the page still auto-scrolls and the user can not turn it off.

**Comment by abarna10** [comment]
Tested and launched.
