### ISSUE TITLE
There is no way to revoke someone's access to a board when they leave the team.

### ISSUE THREAD

**Issue by mtilley1** [FordLabs/retroquest#444]
# Bug report

## Describe the bug
There is no way to revoke a user's access to an existing board if that user knows the board name and password.  There is also no feature that allows for the deletion of a board or ability to change the password of an existing board.

## To Reproduce
N/A - functionality is not available.

## Expected behavior
Built in functionality for the addition and removal of users on a retroquest board.

## Screenshots
Functionality needs to be discussed and designed yet.

## Additional context
We have had a long-term vision for RetroQuest auth to work similar to PeopleMover (minus the audit features).

There are inevitable consequences (pretty much all existing boards would have to get deleted or we'd have to build incredibly complex migration processes to the new login mechanisms), but it might be necessary to do something even if it impacts users.

This is not a "one story" thing, it's a pretty major re-architecting of the entirety of RetroQuest

There has been some domain rework done to be able to facilitate this kind of thing.

**Comment by momraviolio** [comment]
Keeping this as Epic. However Specific issues will be created to aide the transformation to access layers per board/team. 3Q22

**Comment by momraviolio** [comment]
The FordLabs RetroQuest 2022 team has addrressed this issue by adding the workflow to identify a "board owner" role and support the revision of passwords through this role.

RetroQuest shall remain an anonymous tool to capture team comments and improvement opportunities for future work.
