### ISSUE TITLE
Team name is no longer auto filled from URL again

### ISSUE THREAD

**Issue by dbierek** [FordLabs/retroquest#487]
When clicking a link in the form of retroquest.ford.com/login/[team name] the team name input box is not auto filled on the login page. This was working, and then stopped working for a while, then working again, and now it is not working again.

**Comment by RandomAshes** [comment]
@dbierek I just tried it and it is working for me. Can you give me more details on the team name you're using? Does it have spaces or special characters or anything in it? What browser are you using? Anything you can include to help us investigate would be much appreciated.

**Comment by dbierek** [comment]
For sure. Nice, thank you!

**Comment by dbierek** [comment]
Hello again. It looks like the issue is still present. Or team id is fpide2.

**Comment by RandomAshes** [comment]
@dbierek The issue has been resolved, but it has not been shipped to prod yet as we're having to wait for some other features to get approved. It should be fixed in production by later today or tomorrow hopefully.

**Comment by RandomAshes** [comment]
@dbierek It should be fixed now. Please take a look and let me know if it is working for you now.

**Comment by dbierek** [comment]
Yup, just tested it and it is working now. Thanks for your help! 🙌
