### ISSUE TITLE
Thought/Action Item Entry - Add Countdown

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#5]
## Feature Request
The Thought Entry character set is limited.  This request is to add a countdown so a user can understand how many characters they have remaining.

#### Story
**As a** participant of a retrospective
**I want** to understand the number of characters remaining when creating a new Thought or Action Item
**So that** I do not get frustrated with the board suddenly stops accepting new characters as I am creating a new Thought or Action Item

#### Acceptance Criteria
**Given** the participant is a member of a retrospective
**When** they click on the functionality that lets them create a new Thought or Action Item
**Then** they are provided with a visual aid that indicates to them the amount of characters they have remaining before the board stops accepting new characters.

#### Design
This optimal manner in which to provide a visual aid to the user needs to be investigated.

**Comment by Druage** [comment]
Hey I made some UI designs on Friday for this very specific issue. We can run these over with Kyle if we want.

**Comment by Druage** [comment]
![character-countdown](https://user-images.githubusercontent.com/6293337/42172483-14341122-7dea-11e8-841d-b1a8d643e53e.png)

**Comment by Druage** [comment]
![limit-being-reached](https://user-images.githubusercontent.com/6293337/42172484-143fdd90-7dea-11e8-9fd3-c7ed8baaf390.png)

**Comment by Druage** [comment]
We tweaked the UI of the design, we found that the current design did not work too well in actual implementation. We believe the current design is better, we will upload an image of it soon.

**Comment by abarna10** [comment]
This issue has been resolved, tested, and migrated.
