### ISSUE TITLE
Team page background color not filling height w/ scrollbars

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#53]
## Bug report
When the team page has a vertical scrollbar, the background color does not fill past the original page height and extend into this scrollable area.

<img width="788" alt="screen shot 2018-07-13 at 10 45 00 am" src="https://user-images.githubusercontent.com/6293337/42697713-df8f0352-8689-11e8-9585-b8d3f57097a2.png">

**Comment by sgraha75** [comment]
Verified working as expected in DEV

**Comment by abarna10** [comment]
The changes related to this issue have been migrated to PROD.
