### ISSUE TITLE
Use new UI Control Task instead of old Thought component

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#56]
## Feature Request
We need to switch over to using the newly created Task component, which resides in the Controls module. This will simplify the codebase immensely as well as provide a more efficient UX.

#### Design
Check the `styleguide`. They are in there.

<img width="257" alt="screen shot 2018-07-30 at 1 33 32 pm" src="https://user-images.githubusercontent.com/6293337/43413188-5b2cd36a-93fd-11e8-81bb-38b2ed83b53b.png">

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
