### ISSUE TITLE
Enable Cancelling Column Title Edit (ESC key)

### ISSUE THREAD

**Issue by bhoogter** [FordLabs/retroquest#62]
## Feature Request
Allow ESC key to cancel a column header edit.

### Optional user story format:
- When I edit a header
- And am focused into the edit field...
- Allow ESC to cancel the edit mode.

#### Acceptance Criteria
**Given** I am editing a column header...  And am focused into the field...  With or without changes..
**When** I press ESC
**Then** The edit is cancelled and the original contents of the header remain.

**Comment by abarna10** [comment]
This has been shipped and tested in PRDO.
