### ISSUE TITLE
RetroQuest Metrics Trending Over Time

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#69]
## Feature Request
In order to better understanding the growth in user engagement of RetroQuest, we need to start building out metrics related to its usage.

#### Story
**As a** Trusted Committer of RetroQuest
**I Want** to be able to capture and display the following metrics providing an start date (YYYY-MM-DD) and an end date (YYYY-MM-DD)
- Total Number of Reviews
- Total Avg Review Rating (Discard 0 star reviews at the moment. There is no way for a user to input 0 stars as it is the default.)
- Total Number of Team Boards Created
- Total Number of Team Board Logged into
**So That** we can understand how RetroQuest is being used by community and track the metrics over time

**Comment by chiptopher** [comment]
If you were only to provide a start date, should it assume the end date is today?

**Comment by abarna10** [comment]
Yes, no dates would be all time. Only start should default the end date today and only end should default to begin of time.

**Comment by chiptopher** [comment]
When you say Total Number of Team Boards Logged into, does that mean boards that have been logged into more than once, or do you want to keep track of very time a board is logged into?

**Comment by abarna10** [comment]
Code has been deployed to prod. 1 bug was created on team count endpoint.
