### ISSUE TITLE
Use newly redesigned ThoughtDialog

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#74]
## Feature Request
Retroquest needs to start using the newly redesigned dialog for thoughts.

#### Design
![dialog](https://user-images.githubusercontent.com/6293337/43556652-e612a6a8-95ce-11e8-820e-c1f207d53f38.png)

You can check the /styleguide as well.

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
