### ISSUE TITLE
Autofocus Edit Column Title

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#8]
## Feature Request
When editing a column title, the current text should be highlighted by default with the cursor active so a user can just start typing the changes as desired.

#### Story
**As a** facilitator of a retrosepective
**I want** the current text to be highlighted by default when I click the pencil
**So that** I can easily edit the column names without getting frustrated

#### Acceptance Criteria
**Given** the facilitator is setting up a retro board
**When** they click the pencil on a column name
**Then** the text should be focused and highlighted by default

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
