### ISSUE TITLE
TIming race condition on canEditThoughtWithWebsockets test

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#84]
## Bug report
There is a bug within the `canEditThoughtWithWebsockets` test that only shows itself in TravisCI. The issue is that there needs to be more time waited when polling the websocket for the latest message or else this test and possibly others will fail. This should probably be raised to 10 seconds.

**Comment by abarna10** [comment]
This code fix for testing has been shipped to PROD.
