### ISSUE TITLE
Redesign the Feedback dialog!

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#85]
## Feature Request
The feedback dialog doesn't look so hot, it doesn't blend in with the current UI direction at all and it needs to be fixed!

#### Design
![image](https://user-images.githubusercontent.com/6293337/43935968-6a985642-9c24-11e8-9482-49faf94d244f.png)

**Comment by Druage** [comment]
Still needs to scale to mobile support!

**Comment by abarna10** [comment]
@Druage Has this been completed?

**Comment by abarna10** [comment]
This has been developed and migrated to PROD.
