### ISSUE TITLE
Redesign the End Retro Button!

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#86]
## Feature Request
The end retro button probably doesn't need to have feedback in it, nor does it look consistent with the current UI direction and so it should be redesigned and simplified!

#### Design
The design below is really still very much in flux, but this is the general layout and idea.
![image](https://user-images.githubusercontent.com/6293337/43812244-4fbd4ce8-9a8e-11e8-9123-580841ce38d9.png)

**Comment by abarna10** [comment]
The text popup is different that what is displayed above; however, the functionality is working as expected.

**Comment by abarna10** [comment]
Deployed to PROD.
