### ISSUE TITLE
Autofocus Edit Existing Thought

### ISSUE THREAD

**Issue by abarna10** [FordLabs/retroquest#9]
## Feature Request
When editing an existing thought entry, the current text should be highlighted by default with the cursor active so a user can just start typing the changes as desired.

#### Story
**As a** member of a retrospective
**I want** the current text to be highlighted by default when I click the pencil on an existing thought
**So that** I can easily edit the existing thought without getting frustrated

#### Acceptance Criteria
**Given** the member is attending a retro
**When** they click the pencil on an existing thought
**Then** the text should be focused and highlighted by default

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
