### ISSUE TITLE
Update Login Page design

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#90]
## Feature Request
This is a call to update the design on the login page. So now that pretty much all of the UI design has been implemented it is time to come back to the login page. The login page was made mobile friendly but was mean't to a be used as a placeholder for a more consistent design.

#### Design
This is the general idea for the login screen design I envisioned. Obviously, we need the big **RetroQuest** logo back in the top, but from a general idea this is what I have.

**Any thoughts?**

Also, signup is mean't to be something like "Create", I forgot... :|

Here is the first design.
![image](https://user-images.githubusercontent.com/6293337/43926577-c49072aa-9bf8-11e8-8c27-a631c6204cb9.png)

Here is the second one.
![frame 1](https://user-images.githubusercontent.com/6293337/43926837-78361c06-9bf9-11e8-86a8-c96e9d2c0bfc.png)

**Comment by Druage** [comment]
I'm still thinking about this and it's probably going to get held off until we have individual logins.

**Comment by Druage** [comment]
This is done as of PR #124

**Comment by abarna10** [comment]
New Login Page design is now in PROD as expected.
